# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{google_visualization}
  s.version = "0.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Miguel Fonseca"]
  s.date = %q{2010-04-04}
  s.email = %q{fmmfonseca@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/google_visualization.rb",
     "lib/google_visualization/data_cell.rb",
     "lib/google_visualization/data_column.rb",
     "lib/google_visualization/data_element.rb",
     "lib/google_visualization/data_row.rb",
     "lib/google_visualization/data_table.rb",
     "lib/google_visualization/data_type.rb",
     "lib/google_visualization/formatter.rb",
     "lib/google_visualization/formatter/json.rb",
     "tasks/ftp.rake",
     "tasks/rdoc.rake",
     "tasks/test.rake",
     "test/data/table1.json",
     "test/data/table1.rb",
     "test/data/table2.json",
     "test/data/table2.rb",
     "test/data/table3.json",
     "test/data/table3.rb",
     "test/data/table4.json",
     "test/data/table4.rb",
     "test/helper.rb",
     "test/tc_data_cell.rb",
     "test/tc_data_column.rb",
     "test/tc_data_element.rb",
     "test/tc_data_row.rb",
     "test/tc_data_table.rb",
     "test/tc_data_type.rb",
     "test/tc_json.rb"
  ]
  s.homepage = %q{http://github.com/fmmfonseca/google_visualization}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Ruby interface to manipulate and populate data for Google Interactive Charts}
  s.test_files = [
    "test/tc_data_row.rb",
     "test/tc_json.rb",
     "test/tc_data_column.rb",
     "test/tc_data_element.rb",
     "test/tc_data_cell.rb",
     "test/tc_data_table.rb",
     "test/helper.rb",
     "test/data/table4.rb",
     "test/data/table3.rb",
     "test/data/table2.rb",
     "test/data/table1.rb",
     "test/tc_data_type.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

